version: "3.1"

services:
  fda_node_online_cinema:
    # build:
    #   context: ./back
    #   dockerfile: Dockerfile
    image: gelignite/fda_node_online_cinemayyyyyyyyyyyyyyyyyyyyy
    ports:
      - 4200:4200
    restart: always

  fda_next_online_cinema:
    # build:
    #   context: ./front
    #   dockerfile: Dockerfile
    image: gelignite/fda_next_online_cinemayyyyyyyyyyyyyyyyyyyyyyyyy
    ports:
      - 3200:3200
    restart: always
