version: "3.1"

services:
  node:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: gelignite/fda_node_online_cinema
    container_name: fda_node_online_cinema
    # ports:
    #   - 4200:4200
    restart: always
    networks:
      - online-cinema-bridge
  next:
    depends_on:
      - node
    build:
      context: ./front
      dockerfile: Dockerfile
    image: gelignite/fda_next_online_cinema
    container_name: fda_next_online_cinema
    # ports:
    #   - 3200:3200
    restart: always
    networks:
      - online-cinema-bridge
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 83:83
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - www-certbot:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/letsencrypt/:ro
    networks:
      - online-cinema-bridge
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - www-certbot:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw

volumes:
  www-certbot:
# 123
# каждый раз при создании новой сети внутренние ip адреса контейнеров меняются (сейчас 192.168.0.1 и далее по мере создания контейнеров)
# чтобы упорядочить создание контейнеров изпользуем зависимости (depends_on: - next)
networks:
  online-cinema-bridge:
    name: online-cinema
    driver: bridge
