version: "3.1"

services:
  gel/fda_node_online_cinema:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    restart: always

  gel/fda_next_online_cinema:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    restart: always
