version: "3.1"

services:
  node:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: gelignite/fda_node_online_cinema
    container_name: fda_node_online_cinema
    # ports:
    #   - 4200:4200
    restart: always
    networks:
      - online-cinema-bridge
  next:
    depends_on:
      - node
    build:
      context: ./front
      dockerfile: Dockerfile
    image: gelignite/fda_next_online_cinema
    container_name: fda_next_online_cinema
    # ports:
    # - 3200:3200
    restart: always
    networks:
      - online-cinema-bridge
  nginx:
    depends_on:
      - next
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: gelignite/fda_nginx_online_cinema
    container_name: fda_nginx_online_cinema
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - online-cinema-bridge

# каждый раз при создании новой сети внутренние ip адреса контейнеров меняются (сейчас 172.23.0.1 и далее по мере создания контейнеров)
# чтобы упорядочить создание контейнеров изпользуем зависимости (depends_on: - next)
networks:
  online-cinema-bridge:
    name: online-cinema
    driver: bridge
