name: "Workflow Online Cinema"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build-node:
    # runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Change folder
        run: cd back
      - name: Install dependencies
        run: yarn
      - name: Start Node
        run: yarn start
      - name: Success
        run: echo 'Success build Node!'
  build-next:
    # runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Change folder
        run: cd front
      - name: Install dependencies
        run: yarn
      - name: Build Next
        run: yarn build
      - name: Success
        run: echo 'Success build Next'
  deploy:
    needs: [build-node, build-next]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: 217.25.88.33
          user: fda
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd RED-Group_online-cinema;
            git pull;
            make delete;
            make create;
            echo 'Deploy success!';
