name: "Workflow Online Cinema"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    # paths-ignore:
    #   - ".github/workflows/*"
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build-node:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: cd back && yarn
      # - name: Start Node
      #   run: |
      #     cd back
      #     nohup yarn start > /dev/null 2>&1 &
  build-next:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: cd front && yarn
      # - name: Build Next
      #   run: cd front && yarn build
  deploy:
    needs: [build-node, build-next]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run command on remote server
        run: |
          sshpass -p -tt 'Joker!87' ssh fda@217.25.88.33
  # deploy:
  #   needs: [build-node, build-next]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Run command on remote server
  #       uses: D3rHase/ssh-command-action@v0.2.2
  #       with:
  #         host: 217.25.88.33
  #         user: fda
  #         private_key: ${{secrets.SSH_PRIVATE_KEY}}
  #         command: |
  #           cd RED-Group_online-cinema;
  #           git pull;
  #           make delete;
  #           make create;
  #           ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} fda@217.25.88.33 "cd RED-Group_online-cinema && git pull && make delete && make create && echo 'Deploy success!'";
