name: "Workflow Online Cinema"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    # paths-ignore:
    #   - ".github/workflows/*"
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build-node:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: cd back && yarn
      # - name: Start Node
      #   run: |
      #     cd back
      #     nohup yarn start > /dev/null 2>&1 &
  build-next:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: cd front && yarn
      # - name: Build Next
      #   run: cd front && yarn build
  deploy:
    needs: [build-node, build-next]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Connect to remote server
        run: |
          echo "${{ secrets.PASSPHRASE }}" > passphrase.txt
          chmod 600 passphrase.txt
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} -p 22 -o "PasswordAuthentication=no" -o "BatchMode=yes" -o "PreferredAuthentications=publickey" -i passphrase.txt fda@217.25.88.33 "
          cd RED-Group_online-cinema
          # Add your additional commands here
          "
        # uses: appleboy/ssh-action@master
        # with:
        #   host: 217.25.88.33
        #   username: fda
        #   key: ${{ secrets.SSH_PRIVATE_KEY }}
        #   passphrase: ${{ secrets.PASSPHRASE }}
        #   script: |
        #     cd RED-Group_online-cinema
        #     git pull
        #     make delete
        #     make create
        #     echo "Hello, remote server!"
